function [exp_pred, norm_pred] = predict_NB(row, p_y_is_0)
% note: makes use of global variables generated by main2_2 such as
% class_0_muhat
    global class_0_muhat class_1_muhat 
    global class_0_mu class_1_mu class_0_sigma class_1_sigma

    %initialize probabilities
    exp_g0 = log(p_y_is_0);
    exp_g1 = log(1 - p_y_is_0);
    norm_g0 = log(p_y_is_0);
    norm_g1 = log(1 - p_y_is_0);
    
    for i=1:8
        exp_g0 = exp_g0 + log(exppdf(row(i), class_0_muhat(i)));
        exp_g1 = exp_g1 + log(exppdf(row(i), class_1_muhat(i)));
        
        norm_g0 = norm_g0 + log(normpdf(row(i), class_0_mu(i), class_0_sigma(i)));
        norm_g1 = norm_g1 + log(normpdf(row(i), class_1_mu(i), class_1_sigma(i)));
    end
    
    exp_pred = 0;
    if exp_g1 > exp_g0 %higher change of being 1
        exp_pred = 1;
    end
    
    norm_pred = 0;
    if norm_g1 > norm_g0 %higher change of being 1
        norm_pred = 1;
    end
    
end